Add synchronous API
node-eval/file-eval pull request #16
Opened 2017-04-13 15:54 UTC by Yeti-or

2017-04-13 17:29 UTC, blond requested changes

2017-04-13 17:29 UTC, blond commented on package.json
> +    "test:unit": "mocha test/**{,/*}.test.js",
почему текущий вариант не подошёл?

`**` значит в том числе и 0 глубины

2017-04-13 17:29 UTC, blond commented on .travis.yml
> -    - node_js: "0.10"
что послужило причиной?

2017-04-13 17:29 UTC, blond commented on index.js
> +    var fileOpts = prepareOpts(options);
`getFileOpts`?

2017-04-13 17:29 UTC, blond commented on index.js
> +            return contentsEval(stripBom(contents), filename, options && options.context);
От копипаста `contentsEval(stripBom(contents), filename, options && options.context)` лучше тоже избавиться

2017-04-13 18:19 UTC, Yeti-or commented on package.json
> +    "test:unit": "mocha test/**{,/*}.test.js",
а ты точно это у себя пробовал?
а у тебя `bash` или `zsh` ?

2017-04-13 18:20 UTC, Yeti-or commented on .travis.yml
> -    - node_js: "0.10"
то что модуль не работает на 10 ноде:
https://travis-ci.org/node-eval/file-eval/builds/221784499

2017-04-21 19:10 UTC, blond requested changes
Нужно добавить документацию.

2017-04-22 12:38 UTC, blond approved these changes

2017-04-22 12:38 UTC, blond commented on README.md
> +Synchronous version of [fileEval](#fileeval-file-options).
`fileeval-file-options` -> `fileevalfile-options`

2017-04-22 13:18 UTC, merged